#!/usr/bin/env node
// Single source of truth for the skill registry.
// Discovers skills from the filesystem (skills/<category>/<name>/SKILL.md
// frontmatter) and projects them into five artifacts: README.md's table, each
// skills/<category>/README.md, .claude-plugin/plugin.json, skills.sh.json, and
// the config contract mirrored into every skill that reads the config.
//
//   node scripts/gen-skills.ts           # rewrite whichever have drifted
//   node scripts/gen-skills.ts --check   # exit 1 if any is stale (CI)
//   node scripts/gen-skills.ts --paths   # list SKILL.md paths (for scripts)

import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SKILLS_DIR = join(ROOT, 'skills');
const README = join(ROOT, 'README.md');
const PLUGIN = join(ROOT, '.claude-plugin', 'plugin.json');
const SKILLS_SH = join(ROOT, 'skills.sh.json');
const CONFIG_BLOCK = join(ROOT, 'scripts', 'config-block.md');
const RESOLVER = join(ROOT, 'scripts', 'resolve-config.sh');

const START = '<!-- skills:start -->';
const END = '<!-- skills:end -->';
const NOTE =
  '<!-- Generated by `pnpm skills:sync` — edit skill frontmatter, not this table. -->';

// A tag, not an HTML comment: a SKILL.md is a prompt, so the block's boundary should be
// visible to the model reading it rather than hidden in a comment. It carries no
// attributes — provenance would have to name files the installed skill does not have.
// Matched by name, so an attribute added later cannot orphan a committed block.
const CONFIG_OPEN = '<skills-config>';
const CONFIG_OPEN_RE = /<skills-config\b[^>]*>/;
const CONFIG_END = '</skills-config>';

// Node runs this file directly by erasing the types, so only erasable syntax is
// available here: no enums, no namespaces, no parameter properties.
type Category = 'repo' | 'work' | 'docs' | 'meta';

interface Skill {
  category: Category;
  dir: string;
  path: string;
  name: string;
  summary: string;
  frontmatter: { summary?: string; description?: string };
}

interface Group {
  category: Category;
  title: string;
  description: string;
  skills: Skill[];
}

function parseFrontmatter(raw: string): Record<string, string> {
  const match = raw.match(/^---\n([\s\S]*?)\n---/);
  const out: Record<string, string> = {};
  if (!match?.[1]) return out;
  for (const line of match[1].split('\n')) {
    const field = line.match(/^([A-Za-z][\w-]*):\s?(.*)$/);
    const [, key, value] = field ?? [];
    if (key && value) out[key] = value.trim();
  }
  return out;
}

// Fallback when a skill has no `summary`: the first clause of `description`.
function deriveSummary(description: string): string {
  const dash = description.search(/\s[—–]\s/);
  const period = description.search(/\.\s/);
  const stops = [dash, period === -1 ? -1 : period + 1].filter((i) => i > 0);
  let cut = stops.length
    ? description.slice(0, Math.min(...stops)).trim()
    : description.trim();
  if (cut.length > 120) {
    const head = cut.slice(0, 117);
    cut = `${head.slice(0, head.lastIndexOf(' '))}…`;
  }
  return cut;
}

// Skills are nested one level deep: skills/<category>/<skill>/SKILL.md. The
// filesystem owns membership — which skill sits in which category — and this
// table owns each category's display metadata and its order. Adding a skill
// means creating a directory; adding a category means one entry here.
const CATEGORIES: Record<Category, { title: string; description: string }> = {
  repo: {
    title: 'Repository & release',
    description:
      "Commits, pull requests, releases and dependency updates — each driven by the repo's own conventions."
  },
  work: {
    title: 'Tracked work',
    description:
      'Issues, the two AI work loops (implement and review), and handing work between sessions.'
  },
  docs: {
    title: 'Docs & READMEs',
    description:
      'Generate and maintain project documentation, READMEs and terminal demos in the house style.'
  },
  meta: {
    title: 'Meta',
    description: 'Configure the skills themselves, per repo.'
  }
};

function discoverSkills(): Skill[] {
  const categories = readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);

  const unknown = categories.filter((c) => !(c in CATEGORIES));
  if (unknown.length) {
    throw new Error(
      `skills/${unknown.join(', skills/')}: not a known category — add it to CATEGORIES in scripts/gen-skills.ts`
    );
  }

  // Category order comes from CATEGORIES; skills sort alphabetically within one.
  return (Object.keys(CATEGORIES) as Category[])
    .filter((category) => categories.includes(category))
    .flatMap((category) =>
      readdirSync(join(SKILLS_DIR, category), { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => entry.name)
        .sort()
        .map((dir): Skill | null => {
          let raw;
          try {
            raw = readFileSync(
              join(SKILLS_DIR, category, dir, 'SKILL.md'),
              'utf8'
            );
          } catch {
            return null;
          }
          const fm = parseFrontmatter(raw);
          return {
            category,
            dir,
            path: `${category}/${dir}`,
            name: fm.name ?? dir,
            summary: fm.summary ?? deriveSummary(fm.description ?? ''),
            frontmatter: { summary: fm.summary, description: fm.description }
          };
        })
        .filter((skill) => skill !== null)
    );
}

// [{ category, title, description, skills: [...] }] in CATEGORIES order.
function byCategory(skills: Skill[]): Group[] {
  return (
    Object.entries(CATEGORIES) as [Category, (typeof CATEGORIES)[Category]][]
  )
    .map(([category, meta]) => ({
      category,
      ...meta,
      skills: skills.filter((s) => s.category === category)
    }))
    .filter((group) => group.skills.length > 0);
}

function renderTable(groups: Group[]): string {
  const sections = groups.flatMap((group) => [
    '',
    `### ${group.title}`,
    '',
    group.description,
    '',
    '| Skill | Description |',
    '| :-- | :-- |',
    ...group.skills.map(
      (s) => `| [\`${s.name}\`](skills/${s.path}/SKILL.md) | ${s.summary} |`
    )
  ]);
  return [START, NOTE, ...sections, END].join('\n');
}

// Parse the committed block semantically so oxfmt's column alignment and its
// table-padding never trip the drift check. Headings and rows both matter —
// a skill silently moving category has to register as drift.
function parseTable(block: string): string[] {
  const tokens: string[] = [];
  for (const line of block.split('\n')) {
    const heading = line.match(/^###\s+(.*?)\s*$/);
    if (heading) {
      tokens.push(`h\t${heading[1]}`);
      continue;
    }
    const row = line.match(
      /^\|\s*\[`([^`]+)`\]\(([^)]+)\)\s*\|\s*(.*?)\s*\|\s*$/
    );
    if (row) tokens.push(`r\t${row[1]}\t${row[2]}\t${row[3]}`);
  }
  return tokens;
}

function expectedTableTokens(groups: Group[]): string[] {
  return groups.flatMap((group) => [
    `h\t${group.title}`,
    ...group.skills.map(
      (s) => `r\t${s.name}\tskills/${s.path}/SKILL.md\t${s.summary}`
    )
  ]);
}

function syncReadme(groups: Group[], check: boolean): boolean {
  const content = readFileSync(README, 'utf8');
  const from = content.indexOf(START);
  const to = content.indexOf(END);
  if (from === -1 || to === -1) {
    throw new Error(`README.md is missing the ${START} / ${END} markers`);
  }
  const block = content.slice(from, to + END.length);
  const current = parseTable(block);
  const expected = expectedTableTokens(groups);
  const drift = JSON.stringify(current) !== JSON.stringify(expected);
  if (drift && !check) {
    writeFileSync(README, content.replace(block, renderTable(groups)));
  }
  return drift;
}

// One README per category — the section landing a reader hits when they open
// skills/<category>/. Fully generated; edit skill frontmatter, not these.
function renderCategoryReadme(group: Group): string {
  return `${[
    `<!-- Generated by \`pnpm skills:sync\` — edit skill frontmatter, not this file. -->`,
    '',
    `# ${group.title}`,
    '',
    group.description,
    '',
    ...group.skills.map(
      (s) => `- **[${s.name}](./${s.dir}/SKILL.md)** — ${s.summary}`
    ),
    '',
    `Back to [all skills](../README.md).`
  ].join('\n')}\n`;
}

function syncCategoryReadmes(groups: Group[], check: boolean): string[] {
  const stale: string[] = [];
  for (const group of groups) {
    const file = join(SKILLS_DIR, group.category, 'README.md');
    const expected = renderCategoryReadme(group);
    let current = '';
    try {
      current = readFileSync(file, 'utf8');
    } catch {
      current = '';
    }
    // Compare on collapsed whitespace so oxfmt's wrapping never reads as drift.
    const norm = (text: string) => text.replace(/\s+/g, ' ').trim();
    if (norm(current) !== norm(expected)) {
      stale.push(`skills/${group.category}/README.md`);
      if (!check) writeFileSync(file, expected);
    }
  }
  return stale;
}

// skills.sh.json drives how skills.sh displays the collection. Projected from
// the same categories so the website grouping can never drift from the folders.
function syncSkillsSh(groups: Group[], check: boolean): boolean {
  const content = readFileSync(SKILLS_SH, 'utf8');
  const data = JSON.parse(content);
  const expected = groups.map((group) => ({
    title: group.title,
    description: group.description,
    skills: group.skills.map((s) => s.name)
  }));
  const drift =
    JSON.stringify(data.groupings ?? []) !== JSON.stringify(expected);
  if (drift && !check) {
    data.groupings = expected;
    writeFileSync(SKILLS_SH, `${JSON.stringify(data, null, 2)}\n`);
  }
  return drift;
}

function syncPlugin(skills: Skill[], check: boolean): boolean {
  const content = readFileSync(PLUGIN, 'utf8');
  const data = JSON.parse(content);
  const expected = skills.map((s) => `./skills/${s.path}`);
  const drift = JSON.stringify(data.skills ?? []) !== JSON.stringify(expected);
  if (drift && !check) {
    data.skills = expected;
    writeFileSync(PLUGIN, `${JSON.stringify(data, null, 2)}\n`);
  }
  return drift;
}

// A skill can be installed on its own, so it must not link to another skill or to a
// file at the repo root — the link resolves to nothing on the installed copy. Anything
// shared is therefore mirrored *into* each skill and kept identical from here: the
// config contract as text between markers, and the resolver as a real file the skill
// can execute. A skill opts in by carrying the markers.
function configBody(): string {
  const raw = readFileSync(CONFIG_BLOCK, 'utf8');
  const marker = '<!-- config:body -->';
  const at = raw.indexOf(marker);
  if (at === -1) {
    throw new Error(`${CONFIG_BLOCK}: missing ${marker}`);
  }
  return raw.slice(at + marker.length).trim();
}

// The mirrored block opens with a level-3 heading, so it belongs under "## Config".
// Placed anywhere else it silently reads as part of the preceding section — a queue
// skill's block landed under "## Workflow" and became its last step. Rewriting the
// block cannot fix where it sits, so placement is asserted rather than repaired.
function assertPlacement(content: string, from: number, where: string): void {
  const headings = content.slice(0, from).match(/^## .*$/gm);
  const under = headings ? headings[headings.length - 1] : null;
  if (under !== '## Config') {
    throw new Error(
      `${where}: <skills-config> sits under ${under ?? 'no heading'} — move it under a "## Config" heading`
    );
  }
}

function syncConfigContract(skills: Skill[], check: boolean): string[] {
  const stale: string[] = [];
  const expected = `${CONFIG_OPEN}\n\n${configBody()}\n\n${CONFIG_END}`;
  const resolver = readFileSync(RESOLVER, 'utf8');
  // Compare on collapsed whitespace so oxfmt's wrapping never reads as drift.
  const norm = (s: string) => s.replace(/\s+/g, ' ').trim();

  for (const skill of skills) {
    const dir = join(SKILLS_DIR, skill.path);
    let hosts = 0;

    for (const name of ['SKILL.md', 'REFERENCE.md']) {
      const file = join(dir, name);
      let current;
      try {
        current = readFileSync(file, 'utf8');
      } catch {
        continue;
      }
      const opening = current.match(CONFIG_OPEN_RE);
      const to = current.indexOf(CONFIG_END);
      if (!opening || to === -1) continue;
      const from = opening.index as number;
      assertPlacement(current, from, `skills/${skill.path}/${name}`);
      hosts += 1;
      const next =
        current.slice(0, from) +
        expected +
        current.slice(to + CONFIG_END.length);
      if (norm(next) !== norm(current)) {
        stale.push(`skills/${skill.path}/${name} config block`);
        if (!check) writeFileSync(file, next);
      }
    }

    if (!hosts) continue;

    const target = join(dir, 'templates', 'resolve-config.sh');
    let currentResolver = '';
    try {
      currentResolver = readFileSync(target, 'utf8');
    } catch {
      currentResolver = '';
    }
    if (currentResolver !== resolver) {
      stale.push(`skills/${skill.path}/templates/resolve-config.sh`);
      if (!check) {
        mkdirSync(join(dir, 'templates'), { recursive: true });
        writeFileSync(target, resolver);
      }
    }
  }
  return stale;
}

// skills.sh parses real YAML: an unquoted `summary`/`description` must not contain
// ": " (colon+space) or " #" (space+hash), or its parser drops the whole skill — and
// our loose frontmatter regex above would not otherwise catch it.
function lintFrontmatter(skills: Skill[]): string[] {
  const problems: string[] = [];
  for (const skill of skills) {
    for (const field of ['summary', 'description'] as const) {
      const value = skill.frontmatter[field];
      if (!value || /^['"]/.test(value.trim())) continue;
      if (value.includes(': ')) {
        problems.push(
          `${skill.path}: \`${field}\` contains ": " (colon+space) — use " — " instead, else skills.sh drops the skill`
        );
      }
      if (value.includes(' #')) {
        problems.push(
          `${skill.path}: \`${field}\` contains " #" (space+hash) — YAML reads it as a comment`
        );
      }
    }
  }
  return problems;
}

const mode = process.argv[2] ?? '--write';

if (mode === '--paths') {
  for (const skill of discoverSkills()) {
    process.stdout.write(`skills/${skill.path}/SKILL.md\n`);
  }
} else if (mode === '--check' || mode === '--write') {
  const check = mode === '--check';
  const skills = discoverSkills();
  const groups = byCategory(skills);

  const problems = lintFrontmatter(skills);
  if (problems.length) {
    process.stderr.write(
      `skill frontmatter invalid:\n${problems.map((p) => `  - ${p}`).join('\n')}\n`
    );
    process.exit(1);
  }

  const stale: string[] = [];
  if (syncReadme(groups, check)) stale.push('README.md table');
  if (syncPlugin(skills, check)) stale.push('plugin.json skills array');
  if (syncSkillsSh(groups, check)) stale.push('skills.sh.json groupings');
  stale.push(...syncCategoryReadmes(groups, check));
  stale.push(...syncConfigContract(skills, check));

  if (check && stale.length) {
    process.stderr.write(
      `skills registry out of sync: ${stale.join(', ')}\nrun \`pnpm skills:sync\`\n`
    );
    process.exit(1);
  }

  let state = 'already in sync';
  if (check) state = 'in sync';
  else if (stale.length) state = `updated ${stale.join(', ')}`;
  process.stdout.write(`skills registry ${state} (${skills.length} skills)\n`);
} else {
  process.stderr.write(`unknown mode: ${mode}\n`);
  process.exit(2);
}
