#!/usr/bin/env node
// Single source of truth for the skill registry.
// Discovers skills from the filesystem (skills/<category>/<name>/SKILL.md
// frontmatter) and projects them into nine artifacts: README.md's table, each
// skills/<category>/README.md, .claude-plugin/plugin.json, skills.sh.json, the
// config contract mirrored into every skill that reads the config, the
// author-authority block mirrored into every skill that reads third-party text,
// the check-command contract mirrored into every skill that runs the gate, the
// single-flight-lock spec mirrored into the four work-loop skills, and the
// plan-presentation rule mirrored into every skill that presents a plan.
//
//   node scripts/gen-skills.ts           # rewrite whichever have drifted
//   node scripts/gen-skills.ts --check   # exit 1 if any is stale (CI)
//   node scripts/gen-skills.ts --paths   # list SKILL.md paths (for scripts)

import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// Every path the generator touches, derived from one root. The root is an argument
// rather than a module constant because the artifacts are what needs checking, and
// checking them means letting a run produce them: a test points the whole generator
// at a fixture tree and lets it write there. Wired to a constant these functions can
// only ever be run against this repo, which is why none of them had a test.
export interface Paths {
  root: string;
  skills: string;
  readme: string;
  plugin: string;
  skillsSh: string;
  configBlock: string;
  authorityBlock: string;
  verifyBlock: string;
  worklockBlock: string;
  planBlock: string;
  resolver: string;
}

export function paths(root: string): Paths {
  return {
    root,
    skills: join(root, 'skills'),
    readme: join(root, 'README.md'),
    plugin: join(root, '.claude-plugin', 'plugin.json'),
    skillsSh: join(root, 'skills.sh.json'),
    configBlock: join(root, 'scripts', 'config-block.md'),
    authorityBlock: join(root, 'scripts', 'authority-block.md'),
    verifyBlock: join(root, 'scripts', 'verify-block.md'),
    worklockBlock: join(root, 'scripts', 'worklock-block.md'),
    planBlock: join(root, 'scripts', 'plan-block.md'),
    resolver: join(root, 'scripts', 'resolve-config.sh')
  };
}

const START = '<!-- skills:start -->';
const END = '<!-- skills:end -->';
const NOTE =
  '<!-- Generated by `pnpm skills:sync` — edit skill frontmatter, not this table. -->';

// A tag, not an HTML comment: a SKILL.md is a prompt, so the block's boundary should be
// visible to the model reading it rather than hidden in a comment. It carries no
// attributes — provenance would have to name files the installed skill does not have.
// Matched by name, so an attribute added later cannot orphan a committed block.
const CONFIG_OPEN = '<skills-config>';
const CONFIG_OPEN_RE = /<skills-config\b[^>]*>/;
const CONFIG_END = '</skills-config>';

// The author-authority rule is the second thing mirrored into skills. It follows the
// config block's mechanic — one source, drift-checked — but in two variants keyed by what
// text a skill acts on: the full rule for skills acting on text from an identifiable
// author, a reduced form for skills reading author-less third-party text. Matched by exact
// literal tag (with the closing `>`), so `<skills-authority>` never accidentally captures
// `<skills-authority-reduced>`.
const AUTHORITY_FULL_OPEN = '<skills-authority>';
const AUTHORITY_FULL_END = '</skills-authority>';
const AUTHORITY_REDUCED_OPEN = '<skills-authority-reduced>';
const AUTHORITY_REDUCED_END = '</skills-authority-reduced>';

// The check command is the third mirrored contract, and the one with the most to lose from
// drift: how a skill reaches for `verify` decides whether it runs the repo's gate or a guess
// at it. Two variants keyed by the tree the command runs in — base for the working tree,
// isolated for someone else's head, where nothing is installed. Same exact-literal matching
// as above, so `<skills-verify>` never captures `<skills-verify-isolated>`.
const VERIFY_BASE_OPEN = '<skills-verify>';
const VERIFY_BASE_END = '</skills-verify>';
const VERIFY_ISOLATED_OPEN = '<skills-verify-isolated>';
const VERIFY_ISOLATED_END = '</skills-verify-isolated>';

// The fourth mirrored contract, and the one that had to be mirrored rather than cited:
// both queues pointed at `work-implement`'s REFERENCE for the lock spec — a pointer that
// resolves to nothing on an installed copy — and then wrote the load-bearing half out
// again anyway, in two wordings that had already diverged by a clause.
const WORKLOCK_OPEN = '<skills-worklock>';
const WORKLOCK_END = '</skills-worklock>';

// The fifth mirrored contract, and the only one about the skill's *output*: a plan is read
// once, in a terminal, so it has to render there. Every other contract here is about what a
// skill reads or runs; this one is about what arrives in front of the human deciding. It was
// mirrored rather than written per skill because the failure it prevents is silent — a plan
// folded into `<details>` prints its summary and nothing else — and every plan-presenting
// skill is one wording away from re-inventing it.
const PLAN_OPEN = '<skills-plan>';
const PLAN_END = '</skills-plan>';

// The Agent Skills spec caps `description` at 1024 characters, and that cap is a cliff:
// a skill one character over is non-conformant, and nothing about writing a description
// makes its length visible. So the budget enforced here is the lower one — the house
// budget — leaving 64 characters of shoulder above it. That is roughly one trigger phrase
// plus its other-language variant, so the ordinary reason a description gets edited never
// has to be length-neutral, and going over is caught while the skill is still conformant.
const DESCRIPTION_CAP = 1024;
const DESCRIPTION_BUDGET = 960;

// Node runs this file directly by erasing the types, so only erasable syntax is
// available here: no enums, no namespaces, no parameter properties.
type Category = 'repo' | 'work' | 'docs' | 'meta';

export interface Skill {
  category: Category;
  dir: string;
  path: string;
  name: string;
  summary: string;
  frontmatter: { summary?: string; description?: string };
}

export interface Group {
  category: Category;
  title: string;
  description: string;
  skills: Skill[];
}

// Drift is compared on collapsed whitespace throughout: oxfmt rewraps the mirrored
// markdown and pads the generated tables, so a reflow must not read as a change while a
// reworded sentence still does. Defined once — three copies of this is where the
// artifacts would start disagreeing about what counts as drift.
const norm = (text: string) => text.replace(/\s+/g, ' ').trim();

export function parseFrontmatter(raw: string): Record<string, string> {
  const match = raw.match(/^---\n([\s\S]*?)\n---/);
  const out: Record<string, string> = {};
  if (!match?.[1]) return out;
  // One level of nesting is understood: a key with no inline value (e.g.
  // `metadata:`) becomes the parent of the indented `child: value` lines that
  // follow, flattened to `metadata.child` — where the house `summary` now lives.
  let parent = '';
  for (const line of match[1].split('\n')) {
    let nested: RegExpMatchArray | null = null;
    if (parent) nested = line.match(/^\s+([A-Za-z][\w-]*):\s?(.*)$/);
    if (nested?.[2]) {
      out[`${parent}.${nested[1]}`] = nested[2].trim();
      continue;
    }
    const field = line.match(/^([A-Za-z][\w-]*):\s?(.*)$/);
    const [, key, value] = field ?? [];
    if (!key) continue;
    if (value) {
      out[key] = value.trim();
      parent = '';
    } else {
      parent = key;
    }
  }
  return out;
}

// Fallback when a skill has no `metadata.summary`: the first clause of `description`.
export function deriveSummary(description: string): string {
  const dash = description.search(/\s[—–]\s/);
  const period = description.search(/\.\s/);
  const stops = [dash, period === -1 ? -1 : period + 1].filter((i) => i > 0);
  let cut = stops.length
    ? description.slice(0, Math.min(...stops)).trim()
    : description.trim();
  if (cut.length > 120) {
    const head = cut.slice(0, 117);
    cut = `${head.slice(0, head.lastIndexOf(' '))}…`;
  }
  return cut;
}

// Skills are nested one level deep: skills/<category>/<skill>/SKILL.md. The
// filesystem owns membership — which skill sits in which category — and this
// table owns each category's display metadata and its order. Adding a skill
// means creating a directory; adding a category means one entry here.
const CATEGORIES: Record<Category, { title: string; description: string }> = {
  repo: {
    title: 'Repository & release',
    description:
      "Commits, pull requests, releases and dependency updates — each driven by the repo's own conventions."
  },
  work: {
    title: 'Tracked work',
    description:
      'Issues, the two AI work loops (implement and review), handing work between sessions, and summarising one.'
  },
  docs: {
    title: 'Docs & READMEs',
    description:
      'Generate and maintain project documentation, READMEs and terminal demos in the house style.'
  },
  meta: {
    title: 'Meta',
    description: 'Configure the skills themselves, per repo.'
  }
};

export function discoverSkills(p: Paths): Skill[] {
  const categories = readdirSync(p.skills, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);

  const unknown = categories.filter((c) => !(c in CATEGORIES));
  if (unknown.length) {
    throw new Error(
      `skills/${unknown.join(', skills/')}: not a known category — add it to CATEGORIES in scripts/gen-skills.ts`
    );
  }

  // Category order comes from CATEGORIES; skills sort alphabetically within one.
  return (Object.keys(CATEGORIES) as Category[])
    .filter((category) => categories.includes(category))
    .flatMap((category) =>
      readdirSync(join(p.skills, category), { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => entry.name)
        .sort()
        .map((dir): Skill | null => {
          let raw;
          try {
            raw = readFileSync(
              join(p.skills, category, dir, 'SKILL.md'),
              'utf8'
            );
          } catch (err) {
            // No SKILL.md means the directory is not a skill — skip it. Any other
            // read failure is not that, and swallowing it would drop the skill from
            // all nine artifacts in one silent `--write`, reporting success while
            // deleting a published skill's row, entry and grouping.
            if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
            throw err;
          }
          const fm = parseFrontmatter(raw);
          const summary = fm['metadata.summary'];
          return {
            category,
            dir,
            path: `${category}/${dir}`,
            name: fm.name ?? dir,
            summary: summary ?? deriveSummary(fm.description ?? ''),
            frontmatter: { summary, description: fm.description }
          };
        })
        .filter((skill) => skill !== null)
    );
}

// [{ category, title, description, skills: [...] }] in CATEGORIES order.
export function byCategory(skills: Skill[]): Group[] {
  return (
    Object.entries(CATEGORIES) as [Category, (typeof CATEGORIES)[Category]][]
  )
    .map(([category, meta]) => ({
      category,
      ...meta,
      skills: skills.filter((s) => s.category === category)
    }))
    .filter((group) => group.skills.length > 0);
}

export function renderTable(groups: Group[]): string {
  const sections = groups.flatMap((group) => [
    '',
    `### ${group.title}`,
    '',
    group.description,
    '',
    '| Skill | Description |',
    '| :-- | :-- |',
    ...group.skills.map(
      (s) => `| [\`${s.name}\`](skills/${s.path}/SKILL.md) | ${s.summary} |`
    )
  ]);
  return [START, NOTE, ...sections, END].join('\n');
}

// Parse the committed block semantically so oxfmt's column alignment and its
// table-padding never trip the drift check. Headings and rows both matter —
// a skill silently moving category has to register as drift.
export function parseTable(block: string): string[] {
  const tokens: string[] = [];
  for (const line of block.split('\n')) {
    const heading = line.match(/^###\s+(.*?)\s*$/);
    if (heading) {
      tokens.push(`h\t${heading[1]}`);
      continue;
    }
    const row = line.match(
      /^\|\s*\[`([^`]+)`\]\(([^)]+)\)\s*\|\s*(.*?)\s*\|\s*$/
    );
    if (row) tokens.push(`r\t${row[1]}\t${row[2]}\t${row[3]}`);
  }
  return tokens;
}

export function expectedTableTokens(groups: Group[]): string[] {
  return groups.flatMap((group) => [
    `h\t${group.title}`,
    ...group.skills.map(
      (s) => `r\t${s.name}\tskills/${s.path}/SKILL.md\t${s.summary}`
    )
  ]);
}

export function syncReadme(p: Paths, groups: Group[], check: boolean): boolean {
  const content = readFileSync(p.readme, 'utf8');
  const from = content.indexOf(START);
  const to = content.indexOf(END);
  if (from === -1 || to === -1) {
    throw new Error(`README.md is missing the ${START} / ${END} markers`);
  }
  const block = content.slice(from, to + END.length);
  const current = parseTable(block);
  const expected = expectedTableTokens(groups);
  const drift = JSON.stringify(current) !== JSON.stringify(expected);
  if (drift && !check) {
    writeFileSync(p.readme, content.replace(block, renderTable(groups)));
  }
  return drift;
}

// One README per category — the section landing a reader hits when they open
// skills/<category>/. Fully generated; edit skill frontmatter, not these.
export function renderCategoryReadme(group: Group): string {
  return `${[
    `<!-- Generated by \`pnpm skills:sync\` — edit skill frontmatter, not this file. -->`,
    '',
    `# ${group.title}`,
    '',
    group.description,
    '',
    ...group.skills.map(
      (s) => `- **[${s.name}](./${s.dir}/SKILL.md)** — ${s.summary}`
    ),
    '',
    `Back to [all skills](../README.md).`
  ].join('\n')}\n`;
}

export function syncCategoryReadmes(
  p: Paths,
  groups: Group[],
  check: boolean
): string[] {
  const stale: string[] = [];
  for (const group of groups) {
    const file = join(p.skills, group.category, 'README.md');
    const expected = renderCategoryReadme(group);
    let current = '';
    try {
      current = readFileSync(file, 'utf8');
    } catch {
      current = '';
    }
    if (norm(current) !== norm(expected)) {
      stale.push(`skills/${group.category}/README.md`);
      if (!check) writeFileSync(file, expected);
    }
  }
  return stale;
}

// Two artifacts are one key inside a JSON file the generator does not otherwise own, so
// the mechanic is shared and only the projection differs. Every other key in the file
// survives the rewrite — that is the whole reason this reads and re-serializes rather
// than writing the key's value out on its own.
function syncJsonKey(
  file: string,
  key: string,
  expected: unknown,
  check: boolean
): boolean {
  const data = JSON.parse(readFileSync(file, 'utf8')) as Record<
    string,
    unknown
  >;
  const drift = JSON.stringify(data[key] ?? []) !== JSON.stringify(expected);
  if (drift && !check) {
    data[key] = expected;
    writeFileSync(file, `${JSON.stringify(data, null, 2)}\n`);
  }
  return drift;
}

// skills.sh.json drives how skills.sh displays the collection. Projected from
// the same categories so the website grouping can never drift from the folders.
export function syncSkillsSh(
  p: Paths,
  groups: Group[],
  check: boolean
): boolean {
  return syncJsonKey(
    p.skillsSh,
    'groupings',
    groups.map((group) => ({
      title: group.title,
      description: group.description,
      skills: group.skills.map((s) => s.name)
    })),
    check
  );
}

export function syncPlugin(p: Paths, skills: Skill[], check: boolean): boolean {
  return syncJsonKey(
    p.plugin,
    'skills',
    skills.map((s) => `./skills/${s.path}`),
    check
  );
}

// A skill can be installed on its own, so it must not link to another skill or to a
// file at the repo root — the link resolves to nothing on the installed copy. Anything
// shared is therefore mirrored *into* each skill and kept identical from here: the
// config contract as text between markers, and the resolver as a real file the skill
// can execute. A skill opts in by carrying the markers.
export function configBody(p: Paths): string {
  const raw = readFileSync(p.configBlock, 'utf8');
  const marker = '<!-- config:body -->';
  const at = raw.indexOf(marker);
  if (at === -1) {
    throw new Error(`${p.configBlock}: missing ${marker}`);
  }
  return raw.slice(at + marker.length).trim();
}

// The authority source holds both variants, split by markers: the full body runs from
// `<!-- authority:full -->` to `<!-- authority:reduced -->`, the reduced body from there
// to the end. Each is trimmed and mirrored verbatim into its own tag.
export function authorityBody(p: Paths, variant: 'full' | 'reduced'): string {
  const raw = readFileSync(p.authorityBlock, 'utf8');
  const fullMarker = '<!-- authority:full -->';
  const reducedMarker = '<!-- authority:reduced -->';
  const fullAt = raw.indexOf(fullMarker);
  const reducedAt = raw.indexOf(reducedMarker);
  if (fullAt === -1 || reducedAt === -1 || reducedAt < fullAt) {
    throw new Error(
      `${p.authorityBlock}: missing or misordered ${fullMarker} / ${reducedMarker}`
    );
  }
  return variant === 'full'
    ? raw.slice(fullAt + fullMarker.length, reducedAt).trim()
    : raw.slice(reducedAt + reducedMarker.length).trim();
}

// The verify source runs base body → `<!-- verify:isolated -->` → install section. Unlike the
// authority variants, which are alternatives, `isolated` is base *plus* the install section:
// composed here rather than written out twice, so the half both variants share cannot drift
// against itself inside its own source file.
export function verifyBody(p: Paths, variant: 'base' | 'isolated'): string {
  const raw = readFileSync(p.verifyBlock, 'utf8');
  const baseMarker = '<!-- verify:base -->';
  const isolatedMarker = '<!-- verify:isolated -->';
  const baseAt = raw.indexOf(baseMarker);
  const isolatedAt = raw.indexOf(isolatedMarker);
  if (baseAt === -1 || isolatedAt === -1 || isolatedAt < baseAt) {
    throw new Error(
      `${p.verifyBlock}: missing or misordered ${baseMarker} / ${isolatedMarker}`
    );
  }
  const base = raw.slice(baseAt + baseMarker.length, isolatedAt).trim();
  if (variant === 'base') return base;
  return `${base}\n\n${raw.slice(isolatedAt + isolatedMarker.length).trim()}`;
}

// The worklock source has one body and no variants: both loops need the same spec, and
// which lock path a given loop takes is the one thing each skill states for itself.
export function worklockBody(p: Paths): string {
  const raw = readFileSync(p.worklockBlock, 'utf8');
  const marker = '<!-- worklock:body -->';
  const at = raw.indexOf(marker);
  if (at === -1) {
    throw new Error(`${p.worklockBlock}: missing ${marker}`);
  }
  return raw.slice(at + marker.length).trim();
}

// One body, no variants either: a terminal renders the same for every skill, so what a plan
// may look like does not vary with what the skill is planning.
export function planBody(p: Paths): string {
  const raw = readFileSync(p.planBlock, 'utf8');
  const marker = '<!-- plan:body -->';
  const at = raw.indexOf(marker);
  if (at === -1) {
    throw new Error(`${p.planBlock}: missing ${marker}`);
  }
  return raw.slice(at + marker.length).trim();
}

// The mirrored block opens with a level-3 heading, so it belongs under "## Config".
// Placed anywhere else it silently reads as part of the preceding section — a queue
// skill's block landed under "## Workflow" and became its last step. Rewriting the
// block cannot fix where it sits, so placement is asserted rather than repaired.
export function assertPlacement(
  content: string,
  from: number,
  where: string
): void {
  const headings = content.slice(0, from).match(/^## .*$/gm);
  const under = headings ? headings[headings.length - 1] : null;
  if (under !== '## Config') {
    throw new Error(
      `${where}: <skills-config> sits under ${under ?? 'no heading'} — move it under a "## Config" heading`
    );
  }
}

export function syncConfigContract(
  p: Paths,
  skills: Skill[],
  check: boolean
): string[] {
  const stale: string[] = [];
  const expected = `${CONFIG_OPEN}\n\n${configBody(p)}\n\n${CONFIG_END}`;
  const resolver = readFileSync(p.resolver, 'utf8');

  for (const skill of skills) {
    const dir = join(p.skills, skill.path);
    let hosts = 0;

    for (const name of ['SKILL.md', 'REFERENCE.md']) {
      const file = join(dir, name);
      let current;
      try {
        current = readFileSync(file, 'utf8');
      } catch {
        continue;
      }
      const opening = current.match(CONFIG_OPEN_RE);
      const to = current.indexOf(CONFIG_END);
      if (!opening || to === -1) continue;
      const from = opening.index as number;
      assertPlacement(current, from, `skills/${skill.path}/${name}`);
      hosts += 1;
      const next =
        current.slice(0, from) +
        expected +
        current.slice(to + CONFIG_END.length);
      if (norm(next) !== norm(current)) {
        stale.push(`skills/${skill.path}/${name} config block`);
        if (!check) writeFileSync(file, next);
      }
    }

    if (!hosts) continue;

    const target = join(dir, 'templates', 'resolve-config.sh');
    let currentResolver = '';
    try {
      currentResolver = readFileSync(target, 'utf8');
    } catch {
      currentResolver = '';
    }
    if (currentResolver !== resolver) {
      stale.push(`skills/${skill.path}/templates/resolve-config.sh`);
      if (!check) {
        mkdirSync(join(dir, 'templates'), { recursive: true });
        writeFileSync(target, resolver);
      }
    }
  }
  return stale;
}

// Mirror a tagged block into every skill carrying its tag: one source, drift-checked, the
// mechanic behind both the author-authority rule and the check-command contract. A skill opts
// in by carrying the tag, and each body is a `## ` section — self-delimiting, so unlike the
// config block no placement check is needed. Every carrier is also a config-carrying skill, so
// the resolver these bodies read `$resolved` from is already shipped by syncConfigContract.
//
// Generic rather than one function per contract: the third copy of this loop is where the
// contracts would start disagreeing about what counts as drift.
export function syncTaggedBlock(
  p: Paths,
  skills: Skill[],
  check: boolean,
  label: string,
  variants: { open: string; end: string; body: string }[]
): string[] {
  const stale: string[] = [];

  for (const skill of skills) {
    const dir = join(p.skills, skill.path);
    for (const name of ['SKILL.md', 'REFERENCE.md']) {
      const file = join(dir, name);
      let current = '';
      try {
        current = readFileSync(file, 'utf8');
      } catch {
        continue;
      }
      for (const variant of variants) {
        const from = current.indexOf(variant.open);
        const to = current.indexOf(variant.end);
        if (from === -1 || to === -1) continue;
        const next =
          current.slice(0, from) +
          `${variant.open}\n\n${variant.body}\n\n${variant.end}` +
          current.slice(to + variant.end.length);
        if (norm(next) !== norm(current)) {
          stale.push(`skills/${skill.path}/${name} ${label} block`);
          if (!check) writeFileSync(file, next);
        }
        current = next;
      }
    }
  }
  return stale;
}

// Two frontmatter faults nothing else catches, both silent on the way in.
//
// Length: `description` must stay inside the house budget above — no formatter, linter or
// test measures it otherwise, so a description can drift past the spec cap and still show
// a green board.
//
// Punctuation: skills.sh parses real YAML, so an unquoted `summary`/`description` must not
// contain ": " (colon+space) or " #" (space+hash), or its parser drops the whole skill —
// and our loose frontmatter regex above would not otherwise catch it.
export function lintFrontmatter(skills: Skill[]): string[] {
  const problems: string[] = [];
  for (const skill of skills) {
    // Length is checked on the raw value, quoted or not: a quoted description counts its
    // two quotes, which errs two characters strict rather than two characters lax.
    const description = skill.frontmatter.description;
    if (description && description.length > DESCRIPTION_BUDGET) {
      problems.push(
        `${skill.path}: \`description\` is ${description.length} chars — over the ${DESCRIPTION_BUDGET} house budget (spec cap ${DESCRIPTION_CAP}); trim it, so the next edit does not have to be length-neutral`
      );
    }

    for (const field of ['summary', 'description'] as const) {
      const value = skill.frontmatter[field];
      if (!value || /^['"]/.test(value.trim())) continue;
      if (value.includes(': ')) {
        problems.push(
          `${skill.path}: \`${field}\` contains ": " (colon+space) — use " — " instead, else skills.sh drops the skill`
        );
      }
      if (value.includes(' #')) {
        problems.push(
          `${skill.path}: \`${field}\` contains " #" (space+hash) — YAML reads it as a comment`
        );
      }
    }
  }
  return problems;
}

// One run, as a value: the exit code and the two streams, returned rather than written.
// Everything a run decides — which mode, which artifacts drifted, what the operator is
// told — is then assertable without spawning a process or capturing stdout, and the
// process boundary below stays the only place that talks to the OS.
export interface RunResult {
  code: number;
  stdout: string;
  stderr: string;
}

export function main(argv: string[], root: string = ROOT): RunResult {
  const mode = argv[0] ?? '--write';
  if (mode !== '--paths' && mode !== '--check' && mode !== '--write') {
    return { code: 2, stdout: '', stderr: `unknown mode: ${mode}\n` };
  }

  const p = paths(root);
  const skills = discoverSkills(p);

  if (mode === '--paths') {
    const lines = skills.map((skill) => `skills/${skill.path}/SKILL.md\n`);
    return { code: 0, stdout: lines.join(''), stderr: '' };
  }

  const check = mode === '--check';
  const groups = byCategory(skills);

  const problems = lintFrontmatter(skills);
  if (problems.length) {
    return {
      code: 1,
      stdout: '',
      stderr: `skill frontmatter invalid:\n${problems.map((x) => `  - ${x}`).join('\n')}\n`
    };
  }

  const stale: string[] = [];
  if (syncReadme(p, groups, check)) stale.push('README.md table');
  if (syncPlugin(p, skills, check)) stale.push('plugin.json skills array');
  if (syncSkillsSh(p, groups, check)) stale.push('skills.sh.json groupings');
  stale.push(...syncCategoryReadmes(p, groups, check));
  stale.push(...syncConfigContract(p, skills, check));
  stale.push(
    ...syncTaggedBlock(p, skills, check, 'authority', [
      {
        open: AUTHORITY_FULL_OPEN,
        end: AUTHORITY_FULL_END,
        body: authorityBody(p, 'full')
      },
      {
        open: AUTHORITY_REDUCED_OPEN,
        end: AUTHORITY_REDUCED_END,
        body: authorityBody(p, 'reduced')
      }
    ])
  );
  stale.push(
    ...syncTaggedBlock(p, skills, check, 'verify', [
      {
        open: VERIFY_BASE_OPEN,
        end: VERIFY_BASE_END,
        body: verifyBody(p, 'base')
      },
      {
        open: VERIFY_ISOLATED_OPEN,
        end: VERIFY_ISOLATED_END,
        body: verifyBody(p, 'isolated')
      }
    ])
  );
  stale.push(
    ...syncTaggedBlock(p, skills, check, 'worklock', [
      { open: WORKLOCK_OPEN, end: WORKLOCK_END, body: worklockBody(p) }
    ])
  );
  stale.push(
    ...syncTaggedBlock(p, skills, check, 'plan', [
      { open: PLAN_OPEN, end: PLAN_END, body: planBody(p) }
    ])
  );

  if (check && stale.length) {
    return {
      code: 1,
      stdout: '',
      stderr: `skills registry out of sync: ${stale.join(', ')}\nrun \`pnpm skills:sync\`\n`
    };
  }

  let state = 'already in sync';
  if (check) state = 'in sync';
  else if (stale.length) state = `updated ${stale.join(', ')}`;
  return {
    code: 0,
    stdout: `skills registry ${state} (${skills.length} skills)\n`,
    stderr: ''
  };
}

// The process boundary, and the whole of it. Importing this file runs no I/O.
if (import.meta.main) {
  const result = main(process.argv.slice(2));
  if (result.stdout) process.stdout.write(result.stdout);
  if (result.stderr) process.stderr.write(result.stderr);
  process.exit(result.code);
}
