#!/usr/bin/env node
// Single source of truth for the skill registry.
// Discovers skills from the filesystem (skills/<name>/SKILL.md frontmatter)
// and projects them into README.md's table and .claude-plugin/plugin.json.
//
//   node scripts/gen-skills.mjs           # rewrite both, if drifted
//   node scripts/gen-skills.mjs --check   # exit 1 if either is stale (CI)
//   node scripts/gen-skills.mjs --paths   # list SKILL.md paths (for scripts)

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SKILLS_DIR = join(ROOT, 'skills');
const README = join(ROOT, 'README.md');
const PLUGIN = join(ROOT, '.claude-plugin', 'plugin.json');

const START = '<!-- skills:start -->';
const END = '<!-- skills:end -->';
const NOTE =
  '<!-- Generated by `pnpm skills:sync` — edit skill frontmatter, not this table. -->';

function parseFrontmatter(raw) {
  const match = raw.match(/^---\n([\s\S]*?)\n---/);
  const out = {};
  if (!match) return out;
  for (const line of match[1].split('\n')) {
    const field = line.match(/^([A-Za-z][\w-]*):\s?(.*)$/);
    if (field && field[2] !== '') out[field[1]] = field[2].trim();
  }
  return out;
}

// Fallback when a skill has no `summary`: the first clause of `description`.
function deriveSummary(description) {
  const dash = description.search(/\s[—–]\s/);
  const period = description.search(/\.\s/);
  const stops = [dash, period === -1 ? -1 : period + 1].filter((i) => i > 0);
  let cut = stops.length
    ? description.slice(0, Math.min(...stops)).trim()
    : description.trim();
  if (cut.length > 120) {
    const head = cut.slice(0, 117);
    cut = `${head.slice(0, head.lastIndexOf(' '))}…`;
  }
  return cut;
}

function discoverSkills() {
  return readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
    .map((dir) => {
      let raw;
      try {
        raw = readFileSync(join(SKILLS_DIR, dir, 'SKILL.md'), 'utf8');
      } catch {
        return null;
      }
      const fm = parseFrontmatter(raw);
      return {
        dir,
        name: fm.name ?? dir,
        summary: fm.summary ?? deriveSummary(fm.description ?? '')
      };
    })
    .filter((skill) => skill !== null);
}

function renderTable(skills) {
  const rows = skills.map(
    (s) => `| [\`${s.name}\`](skills/${s.dir}/SKILL.md) | ${s.summary} |`
  );
  return [
    START,
    NOTE,
    '',
    '| Skill | Description |',
    '| :-- | :-- |',
    ...rows,
    END
  ].join('\n');
}

// Parse the committed table semantically so oxfmt's column alignment never
// trips the drift check.
function parseTable(block) {
  const rows = [];
  for (const line of block.split('\n')) {
    const m = line.match(/^\|\s*\[`([^`]+)`\]\([^)]+\)\s*\|\s*(.*?)\s*\|\s*$/);
    if (m) rows.push(`${m[1]}\t${m[2]}`);
  }
  return rows;
}

function syncReadme(skills, check) {
  const content = readFileSync(README, 'utf8');
  const from = content.indexOf(START);
  const to = content.indexOf(END);
  if (from === -1 || to === -1) {
    throw new Error(`README.md is missing the ${START} / ${END} markers`);
  }
  const block = content.slice(from, to + END.length);
  const current = parseTable(block);
  const expected = skills.map((s) => `${s.name}\t${s.summary}`);
  const drift = JSON.stringify(current) !== JSON.stringify(expected);
  if (drift && !check) {
    writeFileSync(README, content.replace(block, renderTable(skills)));
  }
  return drift;
}

function syncPlugin(skills, check) {
  const content = readFileSync(PLUGIN, 'utf8');
  const data = JSON.parse(content);
  const expected = skills.map((s) => `./skills/${s.dir}`);
  const drift = JSON.stringify(data.skills ?? []) !== JSON.stringify(expected);
  if (drift && !check) {
    data.skills = expected;
    writeFileSync(PLUGIN, `${JSON.stringify(data, null, 2)}\n`);
  }
  return drift;
}

const mode = process.argv[2] ?? '--write';

if (mode === '--paths') {
  for (const skill of discoverSkills()) {
    process.stdout.write(`skills/${skill.dir}/SKILL.md\n`);
  }
} else if (mode === '--check' || mode === '--write') {
  const check = mode === '--check';
  const skills = discoverSkills();
  const stale = [];
  if (syncReadme(skills, check)) stale.push('README.md table');
  if (syncPlugin(skills, check)) stale.push('plugin.json skills array');

  if (check && stale.length) {
    process.stderr.write(
      `skills registry out of sync: ${stale.join(', ')}\nrun \`pnpm skills:sync\`\n`
    );
    process.exit(1);
  }

  let state = 'already in sync';
  if (check) state = 'in sync';
  else if (stale.length) state = `updated ${stale.join(', ')}`;
  process.stdout.write(`skills registry ${state} (${skills.length} skills)\n`);
} else {
  process.stderr.write(`unknown mode: ${mode}\n`);
  process.exit(2);
}
